export enum AnalyticsNativeEventTypeId {
	SESSION_STARTED = 'SESSION_STARTED',
	BROUGHT_TO_FOREGROUND = 'BROUGHT_TO_FOREGROUND',
	SENT_TO_BACKGROUND = 'SENT_TO_BACKGROUND',
	URL_CHANGED = 'URL_CHANGED',
	API_CALL_ERROR = 'API_CALL_ERROR',
	ACCOUNT_SIGNED_IN = 'ACCOUNT_SIGNED_IN',
	ACCOUNT_SIGNED_OUT = 'ACCOUNT_SIGNED_OUT', // See AnalyticsNativeEventAccountSignedOutSource below
	PAGE_VIEW_SIGN_IN = 'PAGE_VIEW_SIGN_IN',
	PAGE_VIEW_SIGN_IN_EMAIL = 'PAGE_VIEW_SIGN_IN_EMAIL',
	PAGE_VIEW_HOME = 'PAGE_VIEW_HOME',
	PAGE_VIEW_GROUP_SESSIONS = 'PAGE_VIEW_GROUP_SESSIONS',
	PAGE_VIEW_GROUP_SESSION_DETAIL = 'PAGE_VIEW_GROUP_SESSION_DETAIL',
	PAGE_VIEW_PROVIDERS = 'PAGE_VIEW_PROVIDERS',
	PAGE_VIEW_PROVIDER_APPOINTMENT_CONFIRMATION = 'PAGE_VIEW_PROVIDER_APPOINTMENT_CONFIRMATION',
	PAGE_VIEW_MEDICATION_PRESCRIBER = 'PAGE_VIEW_MEDICATION_PRESCRIBER',
	PAGE_VIEW_TOPIC_CENTER = 'PAGE_VIEW_TOPIC_CENTER',
	PAGE_VIEW_RESOURCE_LIBRARY = 'PAGE_VIEW_RESOURCE_LIBRARY',
	PAGE_VIEW_RESOURCE_LIBRARY_TAG_GROUP = 'PAGE_VIEW_RESOURCE_LIBRARY_TAG_GROUP',
	PAGE_VIEW_RESOURCE_LIBRARY_TAG = 'PAGE_VIEW_RESOURCE_LIBRARY_TAG',
	PAGE_VIEW_RESOURCE_LIBRARY_DETAIL = 'PAGE_VIEW_RESOURCE_LIBRARY_DETAIL',
	PAGE_VIEW_MY_EVENTS = 'PAGE_VIEW_MY_EVENTS',
	PAGE_VIEW_CONTACT_US = 'PAGE_VIEW_CONTACT_US',
	PAGE_VIEW_RESOURCE_NAVIGATOR = 'PAGE_VIEW_RESOURCE_NAVIGATOR',
	PAGE_VIEW_FAQS = 'PAGE_VIEW_FAQS',
	PAGE_VIEW_FAQ_DETAIL = 'PAGE_VIEW_FAQ_DETAIL',
	PAGE_VIEW_INSTITUTION_RESOURCES = 'PAGE_VIEW_INSTITUTION_RESOURCES',
	PAGE_VIEW_INSTITUTION_RESOURCE_DETAIL = 'PAGE_VIEW_INSTITUTION_RESOURCE_DETAIL',
	PAGE_VIEW_IN_CRISIS = 'PAGE_VIEW_IN_CRISIS',
	OVERLAY_VIEW_IN_CRISIS = 'OVERLAY_VIEW_IN_CRISIS', // See AnalyticsNativeEventOverlayViewInCrisisSource below
	CLICKTHROUGH_TOPIC_CENTER = 'CLICKTHROUGH_TOPIC_CENTER', // See AnalyticsNativeEventClickthroughTopicCenterSource below
	CLICKTHROUGH_CONTENT = 'CLICKTHROUGH_CONTENT',
	CLICKTHROUGH_FEATURE = 'CLICKTHROUGH_FEATURE', // See AnalyticsNativeEventClickthroughFeatureSource below
}

export enum AnalyticsNativeEventAccountSignedOutSource {
	CONSENT_FORM = 'CONSENT_FORM',
	PATIENT_HEADER = 'PATIENT_HEADER',
	ADMIN_HEADER = 'ADMIN_HEADER',
	MHIC_HEADER = 'MHIC_HEADER',
	ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
	STUDY_ONBOARDING = 'STUDY_ONBOARDING',
}

export enum AnalyticsNativeEventOverlayViewInCrisisSource {
	CONTACT_US = 'CONTACT_US',
	CALL_TO_ACTION = 'CALL_TO_ACTION',
	ERROR_OVERLAY = 'ERROR_OVERLAY',
	PATIENT_HEADER = 'PATIENT_HEADER',
	TRIAGE_RESULTS = 'TRIAGE_RESULTS',
	SCREENING_SESSION = 'SCREENING_SESSION',
}

export enum AnalyticsNativeEventClickthroughTopicCenterSource {
	HOME_FEATURE = 'HOME_FEATURE',
	HOME_SECONDARY_FEATURE = 'HOME_SECONDARY_FEATURE',
	NAV_FEATURE = 'NAV_FEATURE',
	NAV = 'NAV',
}

export enum AnalyticsNativeEventClickthroughFeatureSource {
	HOME = 'HOME',
	NAV = 'NAV',
}
