export enum ENV_VARS {
	COBALT_WEB_API_BASE_URL = 'COBALT_WEB_API_BASE_URL',
	COBALT_WEB_GA_TRACKING_ID = 'COBALT_WEB_GA_TRACKING_ID',
	COBALT_WEB_GA4_MEASUREMENT_ID = 'COBALT_WEB_GA4_MEASUREMENT_ID',
	COBALT_WEB_DISABLE_SIGN_IN = 'COBALT_WEB_DISABLE_SIGN_IN',
	COBALT_WEB_SHOW_DEBUG = 'COBALT_WEB_SHOW_DEBUG',
	COBALT_WEB_SENTRY_SHOW_DEBUG = 'COBALT_WEB_SENTRY_SHOW_DEBUG',
	COBALT_WEB_GOOGLE_MAPS_API_KEY = 'COBALT_WEB_GOOGLE_MAPS_API_KEY',
	COBALT_WEB_LOCALHOST_SUBDOMAIN = 'COBALT_WEB_LOCALHOST_SUBDOMAIN',
	COBALT_WEB_PROVIDER_MANAGEMENT_FEATURE = 'COBALT_WEB_PROVIDER_MANAGEMENT_FEATURE',
	COBALT_WEB_DOWN_FOR_MAINTENANCE = 'COBALT_WEB_DOWN_FOR_MAINTENANCE',
	COBALT_WEB_FINGERPRINTING_ENABLED = 'COBALT_WEB_FINGERPRINTING_ENABLED',
	COBALT_WEB_FINGERPRINTING_TOKEN = 'COBALT_WEB_FINGERPRINTING_TOKEN',
	COBALT_WEB_FINGERPRINTING_ENDPOINT = 'COBALT_WEB_FINGERPRINTING_ENDPOINT',
}

export const AUTH_REDIRECT_URLS = ['/auth', '/mychart/authenticate'];
